/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Morten
 */
public class FiremanGUI extends javax.swing.JFrame {

    /**
     * Creates new form fremDesign
     */
    public FiremanGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstManpower = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        cmbVehicle = new javax.swing.JComboBox();
        txtManHours = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnCH = new javax.swing.JButton();
        btnST = new javax.swing.JButton();
        btnBM = new javax.swing.JButton();
        btnHL = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIncidentTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtIncidentName = new javax.swing.JTextField();
        cmbIncidentType = new javax.swing.JComboBox();
        cmbIncident = new javax.swing.JComboBox();
        lblLogo = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnTeamLeader = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        btnError = new javax.swing.JButton();
        btnFiresuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(null);
        getContentPane().setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mandskab", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel3.setLayout(null);

        lstManpower.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Michael", "Andreas", "Morten" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstManpower);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 40, 240, 430);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Min Indsats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N
        jPanel6.setLayout(null);

        cmbVehicle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vælg Køretøj..." }));
        jPanel6.add(cmbVehicle);
        cmbVehicle.setBounds(20, 40, 180, 40);

        txtManHours.setText("Antal Timer...");
        jPanel6.add(txtManHours);
        txtManHours.setBounds(20, 100, 180, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Funktion"));
        jPanel1.setLayout(null);

        btnCH.setText("CH");
        jPanel1.add(btnCH);
        btnCH.setBounds(100, 20, 80, 40);

        btnST.setText("ST");
        jPanel1.add(btnST);
        btnST.setBounds(10, 20, 80, 40);

        btnBM.setText("BM");
        jPanel1.add(btnBM);
        btnBM.setBounds(10, 70, 80, 40);

        btnHL.setText("HL");
        jPanel1.add(btnHL);
        btnHL.setBounds(100, 70, 80, 40);

        jPanel6.add(jPanel1);
        jPanel1.setBounds(10, 160, 190, 120);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(270, 180, 210, 290);

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("Foto");
        lblImage.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(lblImage);
        lblImage.setBounds(270, 40, 210, 130);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 230, 490, 480);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indsats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("kl.");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(330, 100, 30, 22);

        txtIncidentTime.setText("14.42");
        jPanel4.add(txtIncidentTime);
        txtIncidentTime.setBounds(360, 90, 110, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Dato");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(150, 100, 50, 22);
        jPanel4.add(jDateChooser1);
        jDateChooser1.setBounds(200, 90, 120, 40);

        txtIncidentName.setText("Torvegade 45, 6700 Esbjerg");
        jPanel4.add(txtIncidentName);
        txtIncidentName.setBounds(20, 40, 450, 40);

        cmbIncidentType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indsats" }));
        jPanel4.add(cmbIncidentType);
        cmbIncidentType.setBounds(20, 90, 120, 40);

        cmbIncident.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vælg Anden Indsats..." }));
        jPanel4.add(cmbIncident);
        cmbIncident.setBounds(20, 140, 450, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 20, 490, 200);

        lblLogo.setFont(new java.awt.Font("Calibri", 0, 72)); // NOI18N
        lblLogo.setText("LOGO");
        getContentPane().add(lblLogo);
        lblLogo.setBounds(740, 80, 340, 70);

        btnSave.setText("Gem & Afslut Indsats");
        getContentPane().add(btnSave);
        btnSave.setBounds(1090, 720, 160, 40);

        btnTeamLeader.setText("Hold Leder");
        getContentPane().add(btnTeamLeader);
        btnTeamLeader.setBounds(390, 720, 110, 40);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(520, 250, 10, 10);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fremmødeliste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel5.setLayout(null);

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblAttendance);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(10, 40, 720, 430);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(520, 230, 740, 480);

        btnError.setText("Fejl & Mangler");
        getContentPane().add(btnError);
        btnError.setBounds(240, 720, 130, 40);

        btnFiresuit.setText("Send Brandragt til Vask");
        getContentPane().add(btnFiresuit);
        btnFiresuit.setBounds(40, 720, 180, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiremanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiremanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiremanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiremanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FiremanGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBM;
    private javax.swing.JButton btnCH;
    private javax.swing.JButton btnError;
    private javax.swing.JButton btnFiresuit;
    private javax.swing.JButton btnHL;
    private javax.swing.JButton btnST;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTeamLeader;
    private javax.swing.JComboBox cmbIncident;
    private javax.swing.JComboBox cmbIncidentType;
    private javax.swing.JComboBox cmbVehicle;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JList lstManpower;
    private javax.swing.JTable tblAttendance;
    private javax.swing.JTextField txtIncidentName;
    private javax.swing.JTextField txtIncidentTime;
    private javax.swing.JTextField txtManHours;
    // End of variables declaration//GEN-END:variables
}
