package GUI;

import BE.BEIncidentVehicle;
import BE.BEUsage;
import BE.BEVehicle;
import BLL.BLLFireman;
import GUI.TableModel.TableModelForces;
import GUI.TableModel.TableModelUsage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.TableRowSorter;

public class GUITeamLeader extends javax.swing.JFrame {
    
    TableRowSorter<TableModelUsage> usageSorter;
    TableRowSorter<TableModelForces> forcesSorter;
    private TableModelUsage usageModel;
    private TableModelForces forcesModel;
    private static final ArrayList<BEUsage> EMPTY_USAGE_LIST = new ArrayList<>();
    private static final ArrayList<BEIncidentVehicle> EMPTY_FORCES_LIST = new ArrayList<>();

    /**
     * Creates new form GUITeamLeader
     */
    public GUITeamLeader() {
        initComponents();
        this.setTitle("TOR - Holdleder");
        initializeSettings();
    }
    
    private void initializeSettings() {
        addListeners();
        fillBoxes();
        usageModel = new TableModelUsage(EMPTY_USAGE_LIST);
        forcesModel = new TableModelForces(EMPTY_FORCES_LIST);
        tblUsage.setModel(usageModel);
        tblForces.setModel(forcesModel);
        usageSorter = new TableRowSorter<>(usageModel);
        forcesSorter = new TableRowSorter<>(forcesModel);
        tblUsage.setRowSorter(usageSorter);
        tblForces.setRowSorter(forcesSorter);
        
    }
    
    private void addListeners() {
        btnAction btn = new btnAction();
        txtAction txt = new txtAction();
        txtAmount.addKeyListener(txt);
        txtMaterielAmount.addKeyListener(txt);
        btnAddForces.addActionListener(btn);
        btnAddMateriel.addActionListener(btn);
        btnSaveAndFinish.addActionListener(btn);
    }
    
    private void fillBoxes() {
        fillEmergencyCombo();
        fillMaterialCombo();
        fillReportCombo();
        fillVehicleCombo();
    }
    
    private void fillVehicleCombo() {
        cmbVehicle.addItem(MessageDialog.getInstance().firemanComboVehicle());
        for (BEVehicle bevehicle : BLLFireman.getInstance().readAllVehicles()) {
            cmbVehicle.addItem(bevehicle);
        }
    }
    
    private void fillEmergencyCombo() {
        
    }
    
    private void fillReportCombo() {
        
    }
    
    private void fillMaterialCombo() {
        
    }
    
    private class btnAction implements ActionListener {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            
        }
        
    }
    
    private class txtAction extends KeyAdapter {
        
        @Override
        public void keyReleased(KeyEvent e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cmbVehicle = new javax.swing.JComboBox();
        cbxVariations = new javax.swing.JCheckBox();
        cmbEmergency = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblForces = new javax.swing.JTable();
        btnAddForces = new javax.swing.JButton();
        txtAmount = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmbMaterial = new javax.swing.JComboBox();
        txtMaterielAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsage = new javax.swing.JTable();
        btnAddMateriel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFireReportNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEvaNumber = new javax.swing.JTextField();
        txtIncidentLeader = new javax.swing.JTextField();
        btnSaveAndFinish = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtInvolvedName = new javax.swing.JTextField();
        txtInvolvedAddress = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cmbReport = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        txtDetectorNumber = new javax.swing.JTextField();
        txtGroupNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Eva Rapport Nr");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 40, 150, 22);
        getContentPane().add(txtMessage);
        txtMessage.setBounds(190, 40, 160, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indsatte Styrker", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel1.setLayout(null);

        jPanel1.add(cmbVehicle);
        cmbVehicle.setBounds(20, 30, 140, 40);

        cbxVariations.setText("Afvigelser");
        jPanel1.add(cbxVariations);
        cbxVariations.setBounds(170, 90, 93, 25);

        cmbEmergency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kørsels Type..." }));
        jPanel1.add(cmbEmergency);
        cmbEmergency.setBounds(170, 30, 140, 40);

        tblForces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblForces);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(330, 30, 730, 150);

        btnAddForces.setText("Tilføj");
        jPanel1.add(btnAddForces);
        btnAddForces.setBounds(220, 140, 90, 40);

        txtAmount.setText("Bemanding..");
        jPanel1.add(txtAmount);
        txtAmount.setBounds(20, 80, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 120, 1080, 190);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forbrug", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel2.setLayout(null);

        cmbMaterial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vælg Materiel..." }));
        jPanel2.add(cmbMaterial);
        cmbMaterial.setBounds(18, 32, 290, 40);

        txtMaterielAmount.setText("Forbrug..");
        jPanel2.add(txtMaterielAmount);
        txtMaterielAmount.setBounds(20, 80, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("liter/stk/kg");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 90, 100, 20);

        tblUsage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsage);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(330, 30, 730, 150);

        btnAddMateriel.setText("Tilføj");
        jPanel2.add(btnAddMateriel);
        btnAddMateriel.setBounds(220, 140, 90, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 310, 1080, 190);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Brand Rapport Nr");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 80, 150, 22);
        getContentPane().add(txtFireReportNumber);
        txtFireReportNumber.setBounds(530, 80, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Indsats Leder");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 80, 120, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Melding");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 40, 120, 22);
        getContentPane().add(txtEvaNumber);
        txtEvaNumber.setBounds(530, 40, 160, 30);
        getContentPane().add(txtIncidentLeader);
        txtIncidentLeader.setBounds(190, 80, 160, 30);

        btnSaveAndFinish.setText("Gem og Afslut");
        getContentPane().add(btnSaveAndFinish);
        btnSaveAndFinish.setBounds(960, 660, 140, 40);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oplysninger om skadelidte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Navn");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 30, 120, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Adresse");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 70, 120, 22);
        jPanel3.add(txtInvolvedName);
        txtInvolvedName.setBounds(120, 30, 230, 30);
        jPanel3.add(txtInvolvedAddress);
        txtInvolvedAddress.setBounds(120, 70, 230, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(710, 10, 380, 110);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Beretning", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel4.setLayout(null);

        cmbReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vælg Beretning..." }));
        jPanel4.add(cmbReport);
        cmbReport.setBounds(20, 30, 360, 40);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ved ABA Alarm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N
        jPanel5.setLayout(null);
        jPanel5.add(txtDetectorNumber);
        txtDetectorNumber.setBounds(190, 20, 160, 30);
        jPanel5.add(txtGroupNumber);
        txtGroupNumber.setBounds(190, 70, 160, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setText("Gruppe nummer");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(20, 70, 130, 16);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Detektor nummer");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(20, 30, 140, 16);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(20, 80, 360, 110);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 510, 390, 200);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bemærkninger", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel6.setLayout(null);

        txtRemarks.setColumns(20);
        txtRemarks.setRows(5);
        jScrollPane3.setViewportView(txtRemarks);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(10, 30, 520, 160);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(410, 510, 540, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddForces;
    private javax.swing.JButton btnAddMateriel;
    private javax.swing.JButton btnSaveAndFinish;
    private javax.swing.JCheckBox cbxVariations;
    private javax.swing.JComboBox cmbEmergency;
    private javax.swing.JComboBox cmbMaterial;
    private javax.swing.JComboBox cmbReport;
    private javax.swing.JComboBox cmbVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblForces;
    private javax.swing.JTable tblUsage;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDetectorNumber;
    private javax.swing.JTextField txtEvaNumber;
    private javax.swing.JTextField txtFireReportNumber;
    private javax.swing.JTextField txtGroupNumber;
    private javax.swing.JTextField txtIncidentLeader;
    private javax.swing.JTextField txtInvolvedAddress;
    private javax.swing.JTextField txtInvolvedName;
    private javax.swing.JTextField txtMaterielAmount;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextArea txtRemarks;
    // End of variables declaration//GEN-END:variables
}
