/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guidesign;

/**
 *
 * @author Morten
 */
public class fremDesign extends javax.swing.JFrame {

    /**
     * Creates new form fremDesign
     */
    public fremDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(null);
        getContentPane().setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mandskab", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel3.setLayout(null);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Michael", "Andreas", "Morten" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 50, 240, 280);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Min Indsats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 18))); // NOI18N
        jPanel6.setLayout(null);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vælg Køretøj..." }));
        jPanel6.add(jComboBox4);
        jComboBox4.setBounds(20, 40, 180, 40);

        jTextField2.setText("Antal Timer...");
        jPanel6.add(jTextField2);
        jTextField2.setBounds(20, 100, 180, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Funktion"));
        jPanel1.setLayout(null);

        jButton3.setText("CH");
        jPanel1.add(jButton3);
        jButton3.setBounds(100, 20, 80, 40);

        jButton4.setText("ST");
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 20, 80, 40);

        jButton8.setText("BM");
        jPanel1.add(jButton8);
        jButton8.setBounds(10, 70, 80, 40);

        jButton7.setText("HL");
        jPanel1.add(jButton7);
        jButton7.setBounds(100, 70, 80, 40);

        jPanel6.add(jPanel1);
        jPanel1.setBounds(10, 160, 190, 120);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(270, 40, 210, 290);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 230, 490, 340);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indsats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("kl.");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(330, 100, 30, 22);

        jTextField3.setText("14.42");
        jPanel4.add(jTextField3);
        jTextField3.setBounds(360, 90, 110, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Dato");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(150, 100, 50, 22);
        jPanel4.add(jDateChooser1);
        jDateChooser1.setBounds(200, 90, 120, 40);

        jTextField4.setText("Torvegade 45, 6700 Esbjerg");
        jPanel4.add(jTextField4);
        jTextField4.setBounds(20, 40, 450, 40);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indsats" }));
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(20, 90, 120, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vælg Anden Indsats..." }));
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(20, 140, 450, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 20, 490, 200);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 72)); // NOI18N
        jLabel1.setText("LOGO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(880, 50, 340, 70);

        jButton5.setText("Gem og Afslut Indsats");
        getContentPane().add(jButton5);
        jButton5.setBounds(1090, 580, 160, 40);

        jButton2.setText("Hold Leder");
        getContentPane().add(jButton2);
        jButton2.setBounds(920, 580, 110, 40);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(520, 250, 10, 10);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fremmødeliste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 24))); // NOI18N
        jPanel5.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(10, 40, 720, 290);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(520, 230, 740, 340);

        jButton1.setText("Fejl & Mangler");
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 580, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fremDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fremDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fremDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fremDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fremDesign().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
